tests/area/test_hwloc.c
Fixed the failing test.
The issue arose when the machine has several numanodes.  
The test was assuming a thread pinned by the last numanode and local area chosing first numanode.  
The area was actually working and chosing the last numanode. The test has been fixed to check that the area choses the last numa node instead.
=> Fix area hwloc

include/aml.h
Uniformization of parameter presentation in the documentation.
- put all parameters to @param[in] name format.
- set all function descriptions starting with a verb to infinitive
- set all the parameters descriptions to a start without capitalization
=> Parameters uniformization in doc

configure.ac
Add a small output at the end of configure print the entire
configuration in terms of features/flags, to help users understand what
worked.
=> Have configure output its configuration

include/aml/utils/queue.h, src/utils/async.c, src/utils/queue.c
Fix deadlocks and incoherent state issues in the queue scheduler.
When waiting for a task to finish, the waiter would only look into `doneq` and `workq` for tasks.
If no task is present then the caller was hanging on until a task was ready.
Now, the caller wil not hang anymore when waiting for work done while no task is waiting for execution, being executed or executed. It requires to lock the whole scheduler state and probe all queues for tasks and all threads to see if work in being done.
Therefore, the queue scheduler adds an array of flags that is checked by the waiting caller, along with the queues state
when waiting for a task to finish.
=> [fix] Async Deadlock and Inconsistant State

.github/workflows/style.yml, configure.ac, include/aml/dma/linux.h, include/aml/utils/async.h
The readthedocs builder doesn't always fail on errors. This PR reintroduce our own doc build step to make sure that we're not building bad docs.
=> [ci] improve doc validation

.github/workflows/style.yml, include/aml.h
Wrong flag in the doc nix build check for CI, resulting in new bugs
getting through on the doc building side.
=> [doc/fix] fix typo in doc build checks

src/replicaset/hwloc.c
gettid is a flaky linux-only symbol that might not be available on some
distros and is only used inside aml as part of a corner-case of
replicaset: to load balance between multiple replicas at the same
distance of a thread. Might as well make the load balance an arbitrary
decision and remove the symbol from the library.
=> [fix] remove gettid from aml

.github/workflows/builds.yml, .github/workflows/integration.yml, .github/workflows/style.yml, .gitignore, Makefile.am, autogen.sh, build-aux/git-version-gen, configure.ac, default.nix, include/aml/utils/version.h.in, src/aml.c, tests/utils/test_version.c
Use the git-version-gen file included in recent autoconf distribution
to generate a version string that includes the drift (number of git
commits) since the last tag.
=> [feature] better version string using git

.github/workflows/style.yml
Make sure the job logs always contain the clang format diff for easier
debugging of the style checks.
=> [ci] always displays clang format diff

.github/workflows/builds.yml, .github/workflows/integration.yml, configure.ac, default.nix
In order to ease the spack install process we make a uniform interface to enable/disable backends: hwloc, cuda, opencl, ze.
`--with-<backend>` options are unified by using `pkgconf` m4 macros.
This largely simplifies the work for hwloc and opencl. However, a special attention has to be given to (1) ze and (2) cuda.
(1) ze is not always installed with a `.pc` companion and the detection might fail even if it is installed in a standard path.
Therefore, we provide a fallback method to detect it.
(2) cuda detection is left untouched until we figure out how to deal with nvcc detection and pkg-config for cuda.
In order to customize the installation path of these backends, one can pass `./configure <backend>_CFLAGS <backend>_LDFLAGS` to override pkgconf path. For the case of cuda however, the …
=> Unification of backend activation and path customization

configure.ac
`--with-cuda` options use to allow `<yes|no|cuda_home>` input while other backend would just use the standard yes/no.
cuda_home option is therefore removed and the `CUDA_HOME` environment variable is documented in the configure to 
customize what cuda should be checked.
=> Unify `--with-<backend>` options

src/allocator/area.c, src/allocator/buddy.c, src/area/hip.c
* Undefined behaviors when lock is destroyed before release.
* Not unlocked lock on function exit.
* Non-initialized variable.
=> Various fixes

tests/area/test_hip.c
=> fix uninitialized variable causing a compilation error and a failing test

doc/tutorials/higher/0_deepcopy_linux.c, doc/tutorials/higher/1_deepcopy_cuda.c, include/Makefile.am, include/aml/higher/mapper.h, include/aml/higher/mapper/creator.h, include/aml/higher/mapper/deepcopy.h, include/aml/higher/mapper/visitor.h, include/internal/utstack.h, src/Makefile.am, src/higher/mapper-creator.c, src/higher/mapper-deepcopy.c, src/higher/mapper-visitor.c, src/higher/mapper.c, tests/Makefile.am, tests/higher/test_mapper-creator.c, tests/higher/test_mapper-deepcopy.c, tests/higher/test_mapper-visitor.c, tests/higher/test_mapper.c
This PR lays the foundation for deepcopying and data replication.
The PR keeps the same mapper description but decouples the abstraction for 1. visiting a structure, 2. copying it element by element and 3. Implementing an end to end deepcopy in a single function call. Following these changes, tutorials have been updated to the right deepcopy function calls.
1) The visitor abstraction provides the methods to move around in a data structure, query pointers, compute the total size of a deep structure or even byte-wise comparison of such structures. The abstraction is defined in the header `aml/include/higher/mapper/visitor.h`, implemented in `src/higher/mapper-visitor.c` and tested in `tests/higher/test_mapper-visitor.c`.
2) The creator abstraction provides methods to perform an iterative …
=> Overhaul Mapper Abstraction and Deepcopy

doc/tutorials/area/1_custom_interleave_area.c
This was failing on Crusher login nodes at least (which are 4-way NUMA).
When I instrumented it to figure out what it actually does I noticed that at least on that system it was skipping the highest-number NUMA node so I fixed that as well.
Tested on a 4-node NUMA and a 1-node (non-NUMA) system.
=> Fix to work on a 4-node NUMA

configure.ac, src/Makefile.am
* First and foremost, makes sure that `libaml.so` is linked against its library dependencies. We were carefully setting them in `src/Makefile.am`, only to then ignore them by providing an empty `libaml_la_LDFLAGS`. This has been the case since df3b0f85ea15d20502da97a68388c0fd373293a9. This should fix the smoke test link failures.
* Our configure logic for ZE was broken as well if there was no package config. We were storing the manually obtained results in `ZE_LDFLAGS` instead of the expected `ZE_LIBS`.
* Finally, update to the latest commit of `excit`.
=> Fix dependencies

benchmarks/Makefile.am, configure.ac, doc/tutorials/Makefile.am, src/Makefile.am, tests/Makefile.am
Follow-up to #228. Turns out that libtool filters unknown options out when linking a shared library; and for Intel ZE we need to pass those options undisturbed. There is a way to do it, by prefixing each such options with a libtool-specific `-XCClinker`. I had to whip up an ugly shell script as `Makefile.am` didn't like me using things like make's `patsubst`...
=> Pass OpenMP options to the linker undisturbed

.valgrind.supp, include/aml/dma/cuda.h, include/aml/dma/hip.h, src/dma/cuda.c, src/dma/hip.c, src/utils/async.c, src/utils/queue.c
Next batch of fixes.
* Reimplement the work queue to use condition variables (and sleeping) instead of busy-looping.
* Suppress erroneous errors reported by Helgrind.
* Fix races in HIP DMA.
* Analogous fixes in CUDA DMA (untested, but given the similarities in the code...).
=> Fix async busywait

src/backend/hwloc.c, tests/area/test_hwloc.c
area_preferred relies on qsort for sorting numa nodes. qsort expects negative,0,positive return values, instead of just 0,1.
=> [fix] wrong comparison implementation

.github/workflows/style.yml, default.nix, doc/tutorials/hello_world/hello_world.rst, shell.nix
=> [ci] update clang and nix versions
